[package]
name = "state-get-delete"
authors = ["Jiaxiao Zhou (Mossaka) <duibao55328@gmail.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "2.2.0"

[workspace]
